name: whatsinit
description: A new Flutter project.

publish_to: "none"

version: 1.2.0+4

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  auto_route: ^7.8.4
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  firebase_ui_auth: ^1.13.0
  flutter:
    sdk: flutter
  flutter_html: null
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.4.8
  flutter_screenutil: ^5.9.0
  fluttertoast: ^8.2.4
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  google_generative_ai: ^0.2.2
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  html: ^0.15.4
  image_picker: ^1.0.6
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.19.0
  json_annotation: ^4.8.1
  loading_animation_widget: ^1.2.0+4
  lottie: ^3.1.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.0
  pinput: ^3.0.1
  pretty_dio_logger: ^1.3.1
  pull_to_refresh: ^2.0.0
  qr_code_scanner: ^1.0.1
  webview_flutter: ^4.4.2

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  riverpod_lint: null

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icon/
    - assets/lottie_json/
  fonts:
    - family: couture
      fonts:
        - asset: assets/fonts/couture-bldit.otf
          style: italic
        - asset: assets/fonts/couture-bld.otf
          weight: 700
