// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwTYmcqGrZ2hW_a2hfcZS0mgUrj-CFD1s',
    appId: '1:527300572363:android:c216e4e7491b47e4bd574e',
    messagingSenderId: '527300572363',
    projectId: 'whatsinit-cb62f',
    storageBucket: 'whatsinit-cb62f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiG0JLMVWOALdf5jUG3M-2ngHSF3GDMxM',
    appId: '1:527300572363:ios:5ada5e041d0f86aabd574e',
    messagingSenderId: '527300572363',
    projectId: 'whatsinit-cb62f',
    storageBucket: 'whatsinit-cb62f.appspot.com',
    androidClientId: '527300572363-fng27vnd9eqtb3u41flid30eq0ipn9vt.apps.googleusercontent.com',
    iosClientId: '527300572363-98mftd624f0s6fahrst7q8sm9ur8at5q.apps.googleusercontent.com',
    iosBundleId: 'com.webskitters.whatsinit',
  );

}